#include "BeebVideoULA.h"
#include "CRTC6845.h"
#include "TT5050.h"
#include <iomanip>
#include "Utility.h"
#include <chrono>
#include <cmath>
#include <bitset>
#include <iostream>
#include <string>

using namespace std;

// 
// Emulation of the BBC Micro Video ULA.
// 
// The Video ULA sets up the 6847 CRTC.
// 
// The 6845 R12/R13 value is set as follows:
// MODE 0 - 6:	screen address / 8 <=> 0,1,2: 0x3000 => 0x600, 3: 0x4000 => 0x800, 4-5: 0xb00, 6: 0x6000 => 0xc00
// MODE 7:		screen address - (0x7400 ^ 0x2000) => 0x2800 for actual memory address of 0x7c00
// The same logic applies to setting R14/R15 (cursor position)
//
// Mode		CRTC address		Actual Address		Size	Resolution	Visible	Colours		Total		Visible		Total		PixelW*	PixelR	Pixels/byte**
//																		Chars				Lines		Lines		Chars
// 0		 0x600 -  0xfff		0x3000 - 0x7fff		20k		640x256		80x32		2		312			256			128			1		16 MHz	8
// 1		 0x600 -  0xfff		0x3000 - 0x7fff		20k		320x256		40x32		4		312			256			128			2		 8 MHz	4
// 2		 0x600 -  0xfff		0x3000 - 0x7fff		20k		160x256		20x32		16		312			256			128			4		 4 MHz	2
// 3		 0x800 -  0xfff		0x4000 - 0x7fff		16k		N/A			80x25		2		312			256			128			1		16 MHz	8
// 4		 0xb00 -  0xfff		0x5800 - 0x7fff		10k		320x256		40x32		2		312			256			64			2		 8 MHz	8
// 5		 0xb00 -  0xfff		0x5800 - 0x7fff		10k		160x256		20x32		4		312			256			64			4		 4 MHz	4
// 6		 0xc00 -  0xfff		0x6000 - 0x7fff		8k		N/A			40x25		2		312			256			64			2		 8 MHz	8
// 7		0x2800 - 0x2c00		0x7c00 - 0x7fff		1k		78x75		40x25		8		572			513			64 (768)	1		 8 MHz	12
//															(468x500) (240x250)
//																	  (480x500)
// 
// * W.r.t. scaling to either 640 pixels (Modes 0-6) or 480 pixels (mode 7). For Modes 0-6 PixelW = 16/PixelR; for Mode 7 it is '1'.
// ** For modes 0-6 it is 8/log2(#colours) or 8 * #columns / visible line chars; for mode 7 it is 12.
// 
// Each n x 8(10) pixel block in modes 0-6 are organised so that each row (0,1,..7(9)) of the n pixel are stored
// in consecutive memory locations (row 0: a, row 1: a+1,... row 7: a+7). For two-colour modes n = 8 pixels,
// for 4-colour modes it is 4 pixels and for 16-colour modes it is 2 pixels. That is the reason the screen
// address above is divided by 8. The raster address will then select each of the 8(10) rows to cover the complete
// block of n x 8(10) pixels. The raster rows are 8 for modes 0-2,4 & 5 (graphics & char modes) and 10 for
// modes 3 & 6 (char only modes). The lowest memory address (e.g. 0x5800 for mode 4) will correspond to the
// upper left corner of the screen.
//
// For mode 7 (teletext mode) only complete characters (or graphical symbols) are read at a time and the raster
// address selects the row of each character (the same screen memory data is present for all raster  rows).
// There are for mode 7, 19 raster rows.
// The TCG's page memory input comes from the CRTC (0x7c00 to 0x7fff)
// The TCG then generates either 6 x 10 pixel character colour data (tgc_data)
// or 12 x 20 pixel character colour data (if characters are interpolated).
// The graphics data is always 6 x 10 pixels but encoded as a 2 x 3 sixels (one sixel <=> 3 x 3.3 pixels)
// The visible screen in the should be 480 × 500 pixels <=> 40 × 25 characters <=> 78 x 54 sixels. However,
// The Beeb seems to setup the CRTC to generate only 19 * 25 = 475 (rather than the expected 20 *25 = 500) visible scan lines.
// The full frame rate should correspond to 1/2 the interlaced field rate, i.e. 50 /2 = 25 Hz
//
// IN mode 7, the video data from  the Teletext Character Generator (TGC) is delayed one character column compared with
// the video data generated by the Video ULA itself for non-teletext modes. See below
//						 ,_, ,_, ,_, ,_, ,_, ,_, ,_, ,_, ,_, ,_, ,_,   
// DRAM Clock (4 Mhz)	_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_| |_
//						 .___.   .___.   .___.   .___.   .___.   .___     
// CRTC Clock (1 MHz)	_|   |___|   |___|   |___|   |___|   |___|		The CRTC Clock is 1Mhz for Mode 7; it can however be 2 Mhz for some other modes
//						__.  .____.  .____.  .____.  .____.  .____.
// CRTC Video Adr		  |  | A  |  | A  |  | A  |  | A  |  | A  |
//						--´  `----´  `----´  `----´  `----´  `----´
//						 _.     ._.     ._.     ._.     ._.     ._.
// DRAM Video data		 0|     |1|     |2|     |3|     |4|     |5|		The data is indexed 0,1,2,.. to show the delay w.r.t. TCG video data below
//						 -´     `-´     `-´     `-´     `-´     `-´
//						 .___.   .___.   .___.   .___.   .___.   .___     
// TGC Clock (1 MHz)	_|   |___|   |___|   |___|   |___|   |___|		
//						 _.     ._.     ._.     ._.     ._.     ._.
// TCG Video data		  |     |0|     |1|     |2|     |3|     |4|		The TCG Data comes one 1 Mhz clock cycle after the video data (<=> one char col)
//						 -´     `-´     `-´     `-´     `-´     `-´

BeebVideoULA::BeebVideoULA(
	string name, uint16_t adr, VideoSettings videoSettings, double cpuclock, uint8_t waitStates, ALLEGRO_DISPLAY* disp, ALLEGRO_BITMAP* dispBitmap, DebugManager  *debugManager, ConnectionManager* connectionManager
) : VideoDisplayUnit(name, BEEB_VDU_DEV, videoSettings, cpuclock, waitStates, adr, 0x10, dispBitmap,0x0 /* dummy adr */, debugManager, connectionManager), mDisplay(disp)
{
	//registerPort("SCROLL_CTRL",	IN_PORT,	0x0f, SCROLL_CTRL,	&mSCROLL_CTRL);
	registerPort("C",			IN_PORT,	0x03, C,			&mC);
	registerPort("DISEN",		IN_PORT,	0x01, DISPTMG,		&mDISPTMG);
	registerPort("CURSOR",		IN_PORT,	0x01, CURSOR,		&mCURSOR);	
	registerPort("INV",			IN_PORT,	0x01, INV,			&mINV);
	registerPort("RA",			IN_PORT,	0x0f, RA,			&mRA);
	registerPort("CRTC_CLK",	OUT_PORT,	0x3, CRTC_CLK,		&mCRTC_CLK);

	// Initialise previously read Teletext Character Generator (TGC) data (to a dummy one)
	mTgcData.resize(16);
	for (int i = 0; i < 16; mTgcData[i++] = { 0, 0, 0 });

	// Create display bitmap and clear it
	Resolution vis_res = mVideoSettings.getVisibleResolution();
	mDisplayBitmap = al_create_bitmap(vis_res.width, vis_res.height);
	al_clear_to_color(black);

	if (DBG_LEVEL_DEV(this,DBG_VERBOSE))
		cout << "create display bitmap " << dec << vis_res.width << " x " << vis_res.height << "\n";

	lockDisplay();

	// Define the max bitmap pointer value for later use when updating the bitmap
	mMaxDisplayBitmap_p = (BITMAP_PTR) ((LOCKED_BITMAP_PTR) mLockedDisplayBitMap->data + mLockedDisplayBitMap->pitch * vis_res.height);


}

BeebVideoULA::~BeebVideoULA()
{
	al_destroy_bitmap(mDisplayBitmap);
}


// Power on (reset) the device
bool BeebVideoULA::power()
{

	Device::reset();

	mScanLine = 0;

	return true;
}

// Advance until clock cycle stopcycle has been reached
bool BeebVideoULA::advance(uint64_t stopCycle)
{
	uint64_t cycle;

	return advanceLine(cycle);
}

bool BeebVideoULA::advanceLine(uint64_t& endCycle)
{

	bool sync_debug = false;
	bool mem_debug = false;

	vector<TT5050::TTColour> tgc_data(16);

#ifdef VDU_TIME_DEBUG
	auto video_start = chrono::high_resolution_clock::now();
	auto prelude_start = video_start;
#endif
	// Adjust mCycleCount to match the time passed for one scan line
	uint64_t pCycleCount = mCycleCount;
	double scan_line_duration = getScanLineDuration();
	int cycle_count = max(1, (int)round(scan_line_duration * mCPUClock));
	mCycleCount += cycle_count;
	endCycle = mCycleCount;

	// Make sure internal state is up-to-date and synchronised with that of the CRTC
	if (!validateInternalState(mControlRegister))
		return true;

	int hz_sync_pos = getHorizontalSyncPos();
	int hz_sync_width_cfg = getHorizontalSyncWidth();
	int vt_sync_height_cfg = getVerticalSyncHeight();
	int hz_chars = getCharsPerLine();
	int hz_cursor_skew;
	int hz_disp_skew;
	if (mCRTC != NULL)
		mCRTC->getSkew(hz_disp_skew, hz_cursor_skew);
	else {
		hz_disp_skew = 0;
		hz_cursor_skew = 0;
	}
	int hz_active_rows = getActiveCharRows();
	int hz_active_chars = getActiveCharsPerLine();

	int field_offset = fieldScanLineOffset();
	int adjusted_scanline = mScanLine - field_offset;
	int field_unique_lines = mScreenScanLines / 2;
	int field_unique_line = adjusted_scanline / 2;

	// Border settings (set here and not in the loops below to optimimise performance)
	uint32_t border_colour = 0xff0ff000;
	if (field_offset == 1)
		border_colour = 0xffff0000;

	// Cursor settings (set here and not in the loops below to optimimise performance)
	bool clk_2_Mhz = ((mControlRegister >> 4) & 0x1) != 0;
	uint8_t cursor_segments = (mControlRegister >> 5) & 0x7;

	// Calculate horizontal borders
	Resolution total_res = mVideoSettings.getTotalResolution();
	Resolution video_res = mVideoSettings.getVideoResolution();
	Resolution visible_res = mVideoSettings.getVisibleResolution();
	Resolution visible_offset = mVideoSettings.getVisibleOffset();
	Resolution blanking = mVideoSettings.getBlanking();
	int hz_blanking_spec = (int) round((double)hz_chars * blanking.width / total_res.width);
	int hz_visible_pixels = visible_res.width;
	int vt_visible_pixels = visible_res.height;
	int hz_visible_chars = (int)trunc((double)hz_chars * visible_res.width / total_res.width);
	int vt_blanking = blanking.height;

	int hz_visible_char_offset = (int)round((double)hz_sync_pos + hz_chars * visible_offset.width / total_res.width) % hz_chars;

	int hz_video_content = (int)round((double)hz_chars * video_res.width / total_res.width);

	// Calculate vertical borders
	int hz_unique_resolution = hz_active_chars * mPixelsPerCharacter;
	int hz_active_resolution = hz_active_chars * mPixelsPerCharacter * mPixelW;
	int unique_active_chars = hz_unique_resolution / mHzPixelsPerSymbol;
	int unique_active_rows = mActiveLines / mVtPixelsPerRow;

	int vt_visible_line_offset = (mVerticalSyncPos + visible_offset.height) % mScreenScanLines;
	int visible_scan_line = (mScanLine - vt_visible_line_offset + mScreenScanLines) % mScreenScanLines;
	int active_scan_line = mScanLine;
	int field_scan_line = (mScanLine - mVerticalSyncPos + mScreenScanLines) % mScreenScanLines;
	int video_line = (field_scan_line - vt_blanking + mScreenScanLines) % mScreenScanLines;
	int vt_video_lines = mScreenScanLines - vt_blanking;
	
	if (DBG_LEVEL_DEV(this,DBG_VDU) && adjusted_scanline == 100 && mField % 50 == 0) {
		cout << "\n" << dec <<
			"chars per line: " << hz_chars << ", pixels/byte: " << mPixelsPerCharacter << ", pixel width: " << (int)mPixelW << "\n";
		cout << "duration of a line and a field expressed in pixels: " << total_res.width << " x " << total_res.height << "\n";
		cout << "visible resolution: " << hz_visible_pixels << " x " << vt_visible_pixels << "\n";
		cout << "active resolution: " << hz_active_resolution << " x " << mActiveLines << " (" << hz_active_chars << " x " << hz_active_rows << ")\n";
		cout << "unique active resolution: " << hz_unique_resolution << " x " << mActiveLines << " (" << unique_active_chars << " x " << unique_active_rows << ")\n";
		cout << "video chars: " << hz_video_content << " (" << ((double)hz_video_content / hz_chars) << ")" << "\n";
		cout << "visible chars: " << hz_visible_chars << " (" << ((double)hz_visible_chars / hz_chars) << ")" << "\n";
		cout << "active chars: " << hz_active_chars << " (" << ((double)hz_active_chars / hz_chars) << ")" << "\n";
		cout << "hz blanking: " << hz_blanking_spec << " (" << ((double)hz_blanking_spec / hz_chars) << ")" << "\n";
		cout << "hz visible char pos offset: " << hz_visible_char_offset << "\n";
		cout << "visible line offset: " << vt_visible_line_offset << "\n";
		cout <<	"\n";
	}
	
	int field_rate = (int)round(getFieldRate());

	if (adjusted_scanline == mVerticalSyncPos) {
#ifdef VDU_TIME_DEBUG
		if (DBG_LEVEL_DEV(this,DBG_TIME) && mField == 0) {
			cout << dec << "\n";
			cout << "Field Rate: " << dec << field_rate << "\n";
			cout << "Video ULA total (including CRTC & TCG) - ms per sec: " << mVideoULACnt / 1e6 << "\n";
			cout << "Display prelude - ms per sec: " << mPreludeUsCnt / 1e6 << "\n";
			cout << "Display update - ms per sec: " << mDispUsCnt / 1e6 << "\n";
			cout << "Memory read - ms per sec: " << mReadCnt / 1e6 << "\n";
			cout << "CRTC update - ms per sec: " << mCRTCnt / 1e6 << "\n";
			cout << "TT update - ms per sec: " << mTTCnt / 1e6 << "\n";
			cout << "Line update - ms per sec: " << (mLineCnt- mTTCnt- mCRTCnt- mReadCnt) / 1e6 << "\n";
			cout << "Border update - ms per sec: " << mBorderCnt / 1e6 << "\n";
			mVideoULACnt = 0;
			mPreludeUsCnt = 0;
			mDispUsCnt = 0;
			mCRTCnt = 0;
			mTTCnt = 0;
			mCharPixelCnt = 0;
			mBorderCnt = 0;
			mReadCnt = 0;
			mLineCnt = 0;
		}
#endif
		mField = (mField + 1) % field_rate;
	}

	
	if (false && DBG_LEVEL_DEV(this,DBG_VDU))
		cout << "\n\nFIELD #" << field_offset << "(" << mField << "), SCAN LINE " << dec << mScanLine << " (adjusted to " << adjusted_scanline << ")" <<
		", VISIBLE LINE " << visible_scan_line << " (" << vt_visible_pixels << ")" <<
		", ACTIVE LINE " << active_scan_line << " (" << mActiveLines << ")" <<
		")\n";


	bool teletext = getCRField(CR_TELETEXT) == 1;

#ifdef VDU_TIME_DEBUG
	auto prelude_stop = chrono::high_resolution_clock::now();
	auto prelude_dur = chrono::duration_cast<chrono::nanoseconds>(prelude_stop - prelude_start);
	mPreludeUsCnt += prelude_dur.count();
#endif


	if (adjusted_scanline == mVerticalSyncPos) {
	
#ifdef VDU_TIME_DEBUG
		auto disp_start = chrono::high_resolution_clock::now();
#endif

		DBG_LOG(this, DBG_VDU, "UPDATE SCREEN\n");

		// Unlock the screen display (bitmap) so it can be written to
		unlockDisplay();

		// Clear the screen display
		al_clear_to_color(black);

		// Draw the display bitmap including borders to fill the complete screen display
		al_draw_bitmap(mDisplayBitmap, 0, 0, 0);

		// Make the updates visible on the screen display	
		al_flip_display();


		// Lock the screen display (bitmap) again
		lockDisplay();

#ifdef VDU_TIME_DEBUG
		auto disp_stop = chrono::high_resolution_clock::now();
		auto disp_dur = chrono::duration_cast<chrono::nanoseconds>(disp_stop - disp_start);
		mDispUsCnt += disp_dur.count();
#endif

	}



	// Process one scan line (should be 64/128 chars per scan line and the visible part being 20, 40 or 80 chars)
	// Each char is not necessarily the same as character on the screen. "Big Char" is the char visible
	// on the screen and "Char" is actually one byte fetched from memory that only sometimes corresponds
	// to the width of a screen char. 
	BITMAP_PTR line_bitmap_data_p = NULL;
	if (visible_scan_line < vt_visible_pixels) {
		line_bitmap_data_p = (BITMAP_PTR) ((LOCKED_BITMAP_PTR) mLockedDisplayBitMap->data + mLockedDisplayBitMap->pitch * visible_scan_line);
	}

#ifdef DBG_ON
	if (sync_debug || mem_debug) {
		cout << "\n\n";
		cout << dec << setw(3) << mScanLine << " (F" << field_scan_line << ",R" << mCRTC->mCharRow << ") V" << hz_visible_chars << " A" << hz_active_chars << " O" << hz_visible_char_offset << "\n";
		cout << "Pixels/char: " << mPixelsPerCharacter << ", pixel width: " << (int) mPixelW << "\n";
		bool active_line = false;
		for (int char_pos = 0; char_pos < hz_chars; char_pos++) {
			int active_char_pos = (char_pos - hz_disp_skew + hz_chars) % hz_chars;
			if (active_char_pos < hz_active_chars && active_scan_line < mActiveLines) {
				active_line = true;
				break;
			}
		}
		cout << "FIELD " << dec << mField %2 << "\n";
		cout << "FIELD LINE " << dec << field_unique_line << " (" << field_unique_lines << ")\n";
		cout << "SCAN LINE " << dec << mScanLine << " (" << mScreenScanLines << ")\n";
		cout << "ADJUSTED SCAN LINE " << dec << adjusted_scanline << "\n";
		if (active_line)
			cout << "ACTIVE LINE " << dec << active_scan_line << " (" << mActiveLines << ")\n";
		else
			cout << "INACTIVE LINE " << dec << active_scan_line << " (" << mActiveLines << ")\n";
		if (visible_scan_line < vt_visible_pixels)
			cout << "VISIBLE LINE " << dec << visible_scan_line << " (" << vt_visible_pixels << ")\n";
		else
			cout << "INVISIBLE LINE " << dec << visible_scan_line << " (" << vt_visible_pixels << ")\n";
		if (field_scan_line > vt_blanking)
			cout << "VIDEO LINE " << dec << video_line << " (" << vt_video_lines << ")\n";
		else
			cout << "NON-VIDEO (BLANKING) LINE " << dec << video_line << " (" << vt_video_lines << ")\n";
		if (adjusted_scanline >= mVerticalSyncPos && adjusted_scanline < mVerticalSyncPos + vt_sync_height_cfg)
			cout << "*** VERTICAL SYNC ***\n";
	}

	if (sync_debug) {
		cout << "SYN:";
		for (int char_pos = 0; char_pos < hz_chars; char_pos++) {
			if (char_pos >= hz_sync_pos && char_pos < hz_sync_pos + hz_sync_width_cfg)
				cout << "S";
			else
				cout << "_";
		}
		cout << "\nACT:";
		for (int char_pos = 0; char_pos < hz_chars; char_pos++) {
			int active_char_pos = (char_pos - hz_disp_skew + hz_chars) % hz_chars;
			if (active_char_pos < hz_active_chars && active_scan_line < mActiveLines)
				cout << "A";
			else
				cout << "_";
		}
		cout << "\n    ";
		for (int char_pos = 0; char_pos < hz_chars; cout << char_pos++ % 10);
		cout << "\nVIS:";
		for (int char_pos = 0; char_pos < hz_chars; char_pos++) {
			int visible_char_pos = (char_pos - hz_visible_char_offset + hz_chars) % hz_chars;
			if (visible_char_pos < hz_visible_chars)
				cout << "+";
			else
				cout << "_";
		}
		cout << "\nDIS:";
	}
#endif
	BITMAP_PTR bitmap_data_p = line_bitmap_data_p;
	for (int char_pos = 0; char_pos < hz_chars; char_pos++) {

		int visible_char_pos = (char_pos - hz_visible_char_offset + hz_chars) % hz_chars;
		int active_char_pos = (char_pos - hz_disp_skew + hz_chars) % hz_chars;

#ifdef VDU_TIME_DEBUG
		auto line_start = chrono::high_resolution_clock::now();
#endif
		int pos_X = -1;
		int pos_Y = -1;
		if (line_bitmap_data_p != NULL && visible_char_pos < hz_visible_chars) {
			bitmap_data_p = line_bitmap_data_p + visible_char_pos * mPixelsPerCharacter * mPixelW;
			pos_X = visible_char_pos * mPixelsPerCharacter * mPixelW;
			pos_Y = visible_scan_line;
		}
		else {
			bitmap_data_p = NULL;
		}

		// Advance CRTC & TGC one character (visible or not) and get character data (only used for visible char though)
		// the TGC character is only 12 pixels wide (well 16 bit after being extended) whereas the CRTC one is 8 pixels wide!
#ifdef DBG_ON
		if (false && char_pos == 0 && DBG_LEVEL_DEV(this,DBG_VDU))
			cout << "VDU RA = " << dec << (int)mRA << "\n";
#endif
		// Advance the CRT one character at a time
		// If in the active, area, the video memory address containing 
		// character/graphics data is also provided.
		uint16_t crtc_adr, screen_adr;
#ifdef VDU_TIME_DEBUG
		auto crtc_start = chrono::high_resolution_clock::now();
#endif
		if (!mCRTC->getMemFetchAdr(crtc_adr)) {
			cout << "Failed to get address from the CRTC!\n";
			return false;
		}
#ifdef VDU_TIME_DEBUG
		auto crtc_stop = chrono::high_resolution_clock::now();
		auto crtc_dur = chrono::duration_cast<chrono::nanoseconds>(crtc_stop - crtc_start);
		mCRTCnt += crtc_dur.count();
#endif

		// Is the screen (display) in the active area (for non-teletext modes; for teletext mode dis_ena will be updated later on	
		uint8_t dis_ena = false;
		if (!teletext)
			dis_ena = ~(~mDISPTMG | ((mRA >> 3) & 0x1)); // RA3 shall never be set when not in teletext mode as there are only 8 raster lines for modes 0-6

		// Calculate screen address
		if (!teletext) { // Normally modes 0-6 - raster address selected bytes within an 8 row byte block
			screen_adr = crtc_adr * 8 + (mRA & 0x7);
		}
		else { // Normally mode 7
			screen_adr = crtc_adr + (0x7400 ^ 0x2000); // CRTC MA13 is used to select the SA5050 and is cleared by 0x2000
		}
		if (screen_adr >= 0x8000) {
			if (false)
				cout << "SCROLLING - subtracting 0x" << hex << screen_adr << " by 0x" << mHwScrollSub << " for char pos " << dec << 
					char_pos << " and C1:C0 = " << Utility::int2binStr(mC,2) << "\n";
			screen_adr -= mHwScrollSub; // correct for wrap around when hardware scrolling		
		}

		// 
		// Read video memory data
		// Data shall be read from video memory even if the display is not yet enabled
		//
#ifdef VDU_TIME_DEBUG
		auto mem_read_start = chrono::high_resolution_clock::now();
#endif
		uint8_t screen_data;
		if (!mVideoMem->read(screen_adr, screen_data)) {
			cout << "Failed to read video memory at address 0x" << hex << screen_adr << "\n";
			return false;
		}
#ifdef VDU_TIME_DEBUG
		auto mem_read_stop = chrono::high_resolution_clock::now();
		auto mem_read_dur = chrono::duration_cast<chrono::nanoseconds>(mem_read_stop - mem_read_start);
		mReadCnt += mem_read_dur.count();
#endif

		// For teletext modes, decode video memory data as videotext data
		if (teletext) {
#ifdef VDU_TIME_DEBUG
			auto tt_start = chrono::high_resolution_clock::now();
#endif
			// Feed video memory data to the CRTC. Result will be collected the next character column due to
			// delay within the TCG
			memcpy((char*)&tgc_data[0], (char*)&mTgcData[0], 16 * sizeof(tgc_data[0]));
			dis_ena = mValidTgcData;
			mValidTgcData = mTGC->getScreenData(screen_data, mTgcData);
#ifdef VDU_TIME_DEBUG
			auto tt_stop = chrono::high_resolution_clock::now();
			auto tt_dur = chrono::duration_cast<chrono::nanoseconds>(tt_stop - tt_start);
			mTTCnt += tt_dur.count();
#endif
		}
#ifdef DBG_ON
		if (mem_debug) {
			cout << setfill('0') << setw(2) << dec << char_pos << ":" << setw(4) << hex << screen_adr << ":" << setw(2) << (int)screen_data << ":" <<
			"(" << dec << pos_X << "," << pos_Y << ") ";
		}
		
		if (sync_debug) {
			if (dis_ena)
				cout << "D";
			else
				cout << "_";
		}
#endif		
		if (dis_ena && bitmap_data_p != NULL)
			// Active area of an active line
			//
		{

			// Get cursor configuration
			//
			// The video ULA draws each segment in turn, if the corresponding bit is set.
			// Segments 0 and 1 are each 1/40 or 1/80 of the display width.
			// Segment 2 is twice as wide as segment 1 if the CRTC clock rate is 1 MHz; otheriwse it
			// has the same size as segment 1.
			//
			uint8_t cursor_seg_ena = 0x0;
			if (mCURSOR || mCursorSegment > 0 && (mCursorSegment <= 2 || !clk_2_Mhz && mCursorSegment <= 3)) {
				if (mCursorSegment < 0)
					mCursorSegment = 0;
				int shift = (mCursorSegment <= 2 ? mCursorSegment : 2);
				cursor_seg_ena = (cursor_segments >> (2 - shift)) & 0x1;	
#ifdef DBG_ON
				if (false && DBG_LEVEL_DEV(this,DBG_VDU)) {
					cout << "VDU CURSOR " << dec << (int) mCURSOR << ", cursor ena " << (cursor_seg_ena ? "enabled" : "disabled") <<
						", cursor segments '" << setw(3) << bitset<3>(cursor_segments) << "', cursor segment #" << dec << mCursorSegment << 
						", char col " << char_pos << "\n";
				}
#endif
				mCursorSegment++;
			}
			else
				mCursorSegment = -1;

			uint8_t Rs, Gs, Bs;
			uint8_t R, G, B;

			uint8_t mem_data = screen_data; // not for teletext

			//
			//	Columns	Colours	Big Pixels	Real Pixels		Big Pixel Width		Big Pixels/byte		Bytes/line	
			//	20		16		20*8 = 160	640				4					2					80
			//	40		2		40*8 = 320	640				2					8					40
			//	40		4		40*8 = 320	640				2					4					80
			//	80		2		80*8 = 640	640				1					8					80
			// 
			// Big pixels/byte = 8 * cols / Visible "chars" per line
			//
#ifdef VDU_TIME_DEBUG
			auto char_pixel_start = chrono::high_resolution_clock::now();
#endif
			for (int big_pixel = 0; big_pixel < mPixelsPerCharacter; big_pixel++) {

				if (!teletext) {

					// The screen memory byte's b7b5b3b1 is used as address a3a2a1a0 into the 16-bytes palette memory
					// The read palette memory nibble FBiGiRi gives flash state (F) and inverted values of R (Ri), G (Gi) & B (Bi)  
					uint8_t palette_mem_adr = ((mem_data >> 4) & 0x8) | ((mem_data >> 3) & 0x4) | ((mem_data >> 2) & 0x2) | ((mem_data >> 1) & 0x1);
					uint8_t palette_data = mPaletteMem[palette_mem_adr] & 0xf;
					uint8_t Ri = palette_data & 0x1;
					uint8_t Gi = (palette_data >> 1) & 0x1;
					uint8_t Bi = (palette_data >> 2) & 0x1;
					uint8_t F = (palette_data >> 3) & 0x1;
					uint8_t flash = mControlRegister & 0x1;
					uint8_t Fi = 1 - (F & flash);

					Rs = 1-((Ri ^ Fi) & dis_ena);
					Gs = 1-((Gi ^ Fi) & dis_ena);
					Bs = 1-((Bi ^ Fi) & dis_ena);

					// Invert the video if INV is LOW (only for modes 0 to 6 and not for the teletext mode 7)
					// Also scale up from 0:1 to 0:255 for the intensity
					Rs = ((Rs ^ mINV)?255:0);
					Gs = ((Gs ^ mINV)?255:0);
					Bs = ((Bs ^ mINV)?255:0);
						
				}
				else {
					if (big_pixel < tgc_data.size()) {
						Rs = tgc_data[big_pixel].R;
						Gs = tgc_data[big_pixel].G;
						Bs = tgc_data[big_pixel].B;
					}
					else {
						Rs = Gs = Bs = 0;
					}

				}

				// Super-impose the cursor
				uint8_t cursor = (cursor_seg_ena ? 255 : 0);
				R = Rs ^ cursor;
				G = Gs ^ cursor;
				B = Bs ^ cursor;


				// Update display with the R, G & B data
				//uint32_t colour = 0xff000000 | (R ? 0x00ff0000 : 0) | (G ? 0x0000ff00 : 0) | (B ? 0x000000ff : 0);
				uint32_t colour = 0xff000000 | (R << 16) | (G << 8) | B;
				for (int pw = 0; pw < mPixelW && bitmap_data_p < mMaxDisplayBitmap_p; pw++)
					*bitmap_data_p++ = colour;

				if (!teletext)
					mem_data = (mem_data << 1) | 1;
			}
#ifdef VDU_TIME_DEBUG
			auto char_pixel_stop = chrono::high_resolution_clock::now();
			auto char_pixel_dur = chrono::duration_cast<chrono::nanoseconds>(char_pixel_stop - char_pixel_start);
			mCharPixelCnt += char_pixel_dur.count();
#endif

		}

		else {
			
			if (visible_char_pos < hz_visible_chars && bitmap_data_p != NULL) {
#ifdef VDU_TIME_DEBUG
				auto border_start = chrono::high_resolution_clock::now();
#endif

				for (int big_pixel = 0; big_pixel < mPixelsPerCharacter; big_pixel++)
					for (int pw = 0; pw < mPixelW && bitmap_data_p < mMaxDisplayBitmap_p; pw++)
						*bitmap_data_p++ = border_colour;
#ifdef VDU_TIME_DEBUG
				auto border_stop = chrono::high_resolution_clock::now();
				auto border_dur = chrono::duration_cast<chrono::nanoseconds>(border_stop - border_start);
				mBorderCnt += border_dur.count();
#endif
				
			}

		}
#ifdef VDU_TIME_DEBUG
		auto line_stop = chrono::high_resolution_clock::now();
		auto line_dur = chrono::duration_cast<chrono::nanoseconds>(line_stop - line_start);
		mLineCnt += line_dur.count();
#endif
		
	}

	// Clear remaining  right-most pixels that are "left-over" when the hz res is not a multiple of the visible characters per raster line
	if (line_bitmap_data_p != NULL) {
#ifdef VDU_TIME_DEBUG
		auto border_start = chrono::high_resolution_clock::now();
#endif
		Resolution vis_res = mVideoSettings.getVisibleResolution();
		bitmap_data_p = line_bitmap_data_p + hz_visible_chars * mPixelsPerCharacter * mPixelW;
		int n_left_over_pixels = vis_res.width - hz_visible_chars * mPixelsPerCharacter * mPixelW;
		for (int p = 0; p < n_left_over_pixels && bitmap_data_p < mMaxDisplayBitmap_p;p++)
			*bitmap_data_p++ = border_colour;
#ifdef VDU_TIME_DEBUG
		auto border_stop = chrono::high_resolution_clock::now();
		auto border_dur = chrono::duration_cast<chrono::nanoseconds>(border_stop - border_start);
		mBorderCnt += border_dur.count();
#endif
	}

#ifdef VDU_TIME_DEBUG
	auto video_stop = chrono::high_resolution_clock::now();
	auto video_dur = chrono::duration_cast<chrono::nanoseconds>(video_stop - video_start);
	mVideoULACnt += video_dur.count();
#endif

	return true;
}


bool BeebVideoULA::read(uint16_t adr, uint8_t& data)
{
	// Call parent class to trigger scheduling of other devices when applicable
	if (!VideoDisplayUnit::triggerBeforeRead(adr, data))
		return false;

	// All registers are write-only => return 0xff for read operations
	data = 0xff;

	return true;
}

bool BeebVideoULA::dump(uint16_t adr, uint8_t& data)
{
	data = 0xff;
	return false;
}

// Resize screen if it doesn't already have the correct size
void BeebVideoULA::updateScreenSz(int fullW, int fullH, int activeW, int activeH)
{
	if (fullW != mScreenW || fullH != mScreenH) {
		mScreenW = fullW;
		mScreenH = fullH;
		if (DBG_LEVEL_DEV(this,DBG_VERBOSE))
			cout << "create display bitmap " << dec << mScreenW << " x " << mScreenH << " (" << activeW << " x " << activeH << ")\n";
		al_resize_display(mDisplay, mScreenW, mScreenH);
		unlockDisplay();
		al_destroy_bitmap(mDisplayBitmap);	
		mDisplayBitmap = al_create_bitmap(mScreenW, mScreenH);
		al_set_new_bitmap_flags(mBitMapFlags);
		al_clear_to_color(black);
		lockDisplay();
		mMaxDisplayBitmap_p = (BITMAP_PTR) ((LOCKED_BITMAP_PTR) mLockedDisplayBitMap->data + mLockedDisplayBitMap->pitch * mScreenH);
	}
}

bool BeebVideoULA::validateInternalState(uint8_t newControlRegisterValue)
{
	uint8_t old_control_register_val = mControlRegister;
	mControlRegister = newControlRegisterValue;

	int p_scan_line = mScanLine;
	int p_scan_lines = mScreenScanLines;
	int p_vertical_syn_pos = mVerticalSyncPos;
	int p_pixels_per_byte = mPixelsPerCharacter;

	bool teletext = getCRField(CR_TELETEXT) == 1;
	bool p_teletext = getCRField(old_control_register_val, CR_TELETEXT);

	// Although the scroll context is updated based on C1C0 input changes in processPortUpdate() it could have the wrong value for any mode
	// if the C1C0 inputs are updated BEFORE the Control Register bit for teletext is changed. Therefore update the constant again
	// if the teletext bit was changed.
	if (teletext != p_teletext)
		updateHwScrollConstant();

	if (!initialised()) {
		mScanLine = 0;
		mScreenScanLines = 312;
		mVerticalSyncPos = 280;
		return false;
	}

	mScanLine = getScreenScanLine();
	mScreenScanLines = getScreenScanLines();
	mVerticalSyncPos = getVerticalSyncLine();

	mActiveLines = getActiveLines();

	if (getCRField(CR_CLOCK_RATE) == 1)
		updatePort(CRTC_CLK, 2);
	else
		updatePort(CRTC_CLK, 1);

	mNCols = (1 << getCRField(CR_N_COLS)) * 10;
	mPixelRate = 1 << (getCRField(CR_N_COLS) + 1); // pixel rate: 2, 4, 8 or 16 MHz



	//
	//	Pixels per memory byte (mPixelsPerCharacter), "big" pixels per column symbol (mHzPixelsPerSymbol) and size of "big" pixel (mPixelW)
	//
	//	As configured by the Video ULA Control Register	(CR)							Given by Video ULA PR and additional CRTC configuration
	//	===================================================								==========================================================
	//	No of cols	Pixel rate	Pixels/Byte				CRTC Clk		Colours			Total columns	Pixels/symb				Pixel size	Scr.pix./symb	Modes
	//							(mPixelsPerCharacter)													(mHzPixelsPerSymbol)	(mPixelW)
	//	==========	==========	=====================	========		=======			=============	====================	==========	==============	=====
	//	10			2 MHz		1						
	//	20			4 MHz		2:2 5:4					0-3:2 4-7:1		2:16 5:4		2:128,5:64		8						4			8				2,5
	//	40			8 MHz		1:4 4,6:8 7:N/A			0-3:2 4-7:1		1:4 4,6:2 7:N/A	1:128 4,6,7:64	8 (7:16)				2 (7:1)		8 (7:16)		1,4,6,7
	//	80			16 MHz		8						0-3:2 4-7:1		0,3:2			128				8						1			8				0,3
	//

	// Pixel width in "actual pixels" for a 640-pixel wide screen
	mPixelW = 16 / mPixelRate; 
	if (teletext)
		mPixelW = 1;

	// Pixels per memory byte
	// Round to consider subtle changes in displayed characters per line
	mPixelsPerCharacter = (int)round(8.0 * mNCols / getActiveCharsPerLine());
	if (mPixelsPerCharacter > 8) {
		return false;
	}
	if (teletext)
		mPixelsPerCharacter = 16; // as 12 pixels have been stretched to 16 by the TCG

	// "big" pixels per symbol
	mHzPixelsPerSymbol = 8;
	if (teletext)
		mHzPixelsPerSymbol = 16;

	// Vertical pixels per character row is normally the same as twice the no of raster lines
	// except for the interlace video mode where it is identical to the raster lines
	mVtPixelsPerRow = getCharScanLines();
	if (!mCRTC->interlacedVideo())
		mVtPixelsPerRow *= 2;

#ifdef DBG_ON
	if ((
		((mControlRegister ^ newControlRegisterValue) & 0xfe) != 0 ||
		mPixelsPerCharacter != p_pixels_per_byte ||
		mScreenScanLines != p_scan_lines ||
		mVerticalSyncPos != p_vertical_syn_pos
		)
		&& (DBG_LEVEL_DEV(this,DBG_VERBOSE))
	) {
		cout << "\n" << dec;
		cout << "Video ULA Control Register: 0x" << hex << (int)mControlRegister << dec << "\n";
		cout << "Video ULA PixelRate:       " << mPixelRate << " MHz\n";
		cout << "Video ULA PixelWidth:      " << (int)mPixelW << "\n";
		cout << "Video ULA Pixels/byte:     " << (int)mPixelsPerCharacter << "\n";
		cout << "Video ULA CRTC Clock:      " << (int)mCRTC_CLK << " MHz\n";
		cout << "Video ULA No of cols:      " << dec << mNCols << "\n";
		cout << "Video ULA Teletext:        " << (getCRField(CR_TELETEXT) ? "ON" : "OFF") << "\n";
		cout << "Video ULA Cursor Segments: " << hex << (int)getCRField(CR_CURSOR_SEGMENT) << "\n";
		cout << "Video ULA Pixel Width:     " << dec << (int)mPixelW << "\n";
		cout << "Video ULA Pixels/byte:     " << dec << mPixelsPerCharacter << "\n";
		cout << "Video ULA Scan Line:       " << dec << mScanLine << "\n";
		cout << "Video ULA Scan Lines:      " << dec << mScreenScanLines << "\n";
		cout << "Video ULA Vertical Sync:   " << dec << mVerticalSyncPos << "\n";
		cout << "\n";
	}
#endif
	

	return true;
}

bool BeebVideoULA::write(uint16_t adr, uint8_t data)
{

	if (!VideoDisplayUnit::selected(adr))
		return false;

	uint16_t a = adr - mMemorySpace.adr;

	if (a == 0) {

		validateInternalState(data);

	}
	else if (a == 1) {
		uint8_t pa = (data >> 4) & 0xf;
		mPaletteMem[pa] = data & 0xf;
	}

	
	
	// Call parent class to trigger scheduling of other devices when applicable
	return VideoDisplayUnit::triggerAfterWrite(adr, data);
}

bool BeebVideoULA::readGraphicsMem(uint16_t adr, uint8_t& data)
{
	return true;
}

void BeebVideoULA::lockDisplay()
{
	// Save allegro state and lock display bitmap for update
	al_store_state(&mAllegroState, ALLEGRO_STATE_TARGET_BITMAP);
	al_set_target_bitmap(mDisplayBitmap);
	mLockedDisplayBitMap = al_lock_bitmap(mDisplayBitmap, ALLEGRO_PIXEL_FORMAT_ANY, ALLEGRO_LOCK_WRITEONLY);
}

void BeebVideoULA::unlockDisplay()
{
	// Restore allegro state and unlock display for update
	al_unlock_bitmap(mDisplayBitmap);
	al_restore_state(&mAllegroState);
}


double BeebVideoULA::getScanLineDuration()
{
	if (mCRTC != NULL && mCRTC->initialised())
		return mCRTC->getScanLineDuration();
	else
		return 64.0;
}

double BeebVideoULA::getScanLinesPerField()
{
	if (mCRTC != NULL && mCRTC->initialised())
		return mCRTC->getScanLinesPerField();
	else
		return 312.0;
}

int BeebVideoULA::getScreenScanLines()
{
	if (mCRTC != NULL && mCRTC->initialised())
		return mCRTC->getScreenScanLines();
	else
		return 624;
}

double BeebVideoULA::getFieldRate()
{
	if (mCRTC != NULL && mCRTC->initialised())
		return mCRTC->getFieldRate();
	else
		return 50.0;
}

int BeebVideoULA::getCharScanLines()
{
	if (mCRTC != NULL && mCRTC->initialised())
		return mCRTC->getCharScanLines();
	else
		return 12;
}

int BeebVideoULA::getVerticalSyncLine()
{
	if (mCRTC != NULL && mCRTC->initialised())
		return mCRTC->getVerticalSyncLine();
	else
		return 0;
}

int BeebVideoULA::getVerticalSyncHeight()
{
	if (mCRTC != NULL && mCRTC->initialised())
		return mCRTC->getVerticalSyncHeight();
	else
		return 1;
}

int BeebVideoULA::getHorizontalSyncPos()
{
	if (mCRTC != NULL && mCRTC->initialised())
		return mCRTC->getHorizontalSyncPos();
	else
		return 51;

}

int BeebVideoULA::getCharsPerLine()
{
	if (mCRTC != NULL && mCRTC->initialised())
		return mCRTC->getCharsPerLine();
	else
		return 40;
}

int BeebVideoULA::getActiveCharsPerLine()
{
	if (mCRTC != NULL && mCRTC->initialised())
		return mCRTC->getActiveCharsPerLine();
	else
		return 40;
}

int BeebVideoULA::getScreenScanLine()
{
	return mCRTC->getScreenScanLine();
}

int BeebVideoULA::getActiveLines()
{
	if (mCRTC != NULL && mCRTC->initialised())
		return mCRTC->getActiveLines();
	else
		return 200;
}

int BeebVideoULA::getActiveCharRows()
{
	if (mCRTC != NULL && mCRTC->initialised())
		return mCRTC->getActiveCharRows();
	else
		return 20;
}

int BeebVideoULA::getHorizontalSyncWidth()
{
	if (mCRTC != NULL && mCRTC->initialised())
		return mCRTC->getHorizontalSyncWidth();
	else
		return 2;
}

// Get pointer to other device to be able to call its methods
bool BeebVideoULA::connectDevice(Device* dev)
{
	Device::connectDevice(dev);

	if (dev != NULL && dev->devType == CRTC6845_DEV) {
		mCRTC = (CRTC6845*)dev;
	}
	if (dev != NULL && dev->devType == TT_5050_DEV) {
		mTGC = (TT5050*)dev;
	}

	return true;
}

// Check if interlace is enabled (On)
bool BeebVideoULA::interlaceOn()
{
	return (mCRTC != NULL && mCRTC->interlaceOn());
}

// Advance 1/2 scan line - required for interlace modes as
// each field is usally 312 1/2 (PAL) or 262 1/2 (NTSC) scan lines
// to get 625 (PAL) or 525 (NTSC) scan lines per frame (i.e., a pair of even and odd fields)
// at 50 Hz (PAL) or 60 Hz (NTSC).
bool BeebVideoULA::advanceHalfLine(uint64_t& endCycle)
{
	uint64_t pCycleCount = mCycleCount;
	double half_scan_line_duration = getScanLineDuration() / 2;
	int cycle_count = max(1, (int)round(half_scan_line_duration * mCPUClock));
	mCycleCount += cycle_count;
	endCycle = mCycleCount;

	return true;
}

// Get scan line offset (0 for even field or non-interlaced mode, 1 for odd field)
int BeebVideoULA::fieldScanLineOffset()
{
	if (mCRTC != NULL && mCRTC->initialised())
		return mCRTC->fieldScanLineOffset();
	else
		return 0;
}

void BeebVideoULA::processPortUpdate(int index)
{
	if (index == C) {
		updateHwScrollConstant();
	}

}

//
// Hardware scrolling
// 
// The values of C0 and C1 together determine the value to subtract from the current
// address when it exceeds 8000
//      MA12	C1   C0     CRTC address	Screen				Mem		Hz			subract
//		(a15)								Address   Modes		Sz		Res			const
//		------------------------------------------------------------------------------------
//		0		x	x		2800			7c00		7		1k					0400
//		1		0   0		800				4000		3		16k					4000
//		1		0   1		c00				6000		6		8k					2000
//		1		1	0		600				3000		0,1,2	20k		80 bytes	5000
//		1		1   1		b00				5800		4,5		10k					2800
//
// The System VIA's PB(3:0) are connected to the Video ULA's SCROLL_CTRL(3:0) where
// The three least significant bits selects whether to update C0 (4) or C1 (5)
// and the most significant bit is the value to assign to C0 or C1.
// mC = C(1:0) below with C1 as the most significant bit and C0 as the least significant bit.
//
void BeebVideoULA::updateHwScrollConstant() {
	
	uint16_t p_HW_scroll_sub = mHwScrollSub;
	int mode = 0;
	mHwScrollSub = 0x0;
	switch (mC & 0x3) {
	case 0:// Mode 3 - start address 0x4000
		mode = 3;
		mHwScrollSub = 0x4000;
		break;
	case 1: // Mode 6 - start address 0x6000
		mode = 6;
		mHwScrollSub = 0x2000;
		break;
	case 2:// Modes 0,1,2 - start address 0x3000
		mode = 210;
		mHwScrollSub = 0x5000;
		break;
	case 3:// Modes 4,5 - start address 0x5800
		mode = 54;
		mHwScrollSub = 0x2800;
		break;
	default:
		mode = -1;
		break;
	}

	bool teletext = getCRField(CR_TELETEXT) == 1;
	if (teletext) {
		mHwScrollSub = 0x0400;
		mode = 7;
	}
#ifdef DBG_ON
	if (false && DBG_LEVEL_DEV(this,DBG_VDU) && mHwScrollSub != p_HW_scroll_sub) {
		cout << "Teletext=" << (int)teletext << ", C1C0=0x" << hex << (int)mC << " => new HW Scroll constant 0x" << hex << mHwScrollSub << " (0x" << p_HW_scroll_sub << ") for mode " << dec << mode << "\n";
		cout << "Video ULA CR = 0x" << hex << (int)mControlRegister << "\n";
	}
#endif
}
