#ifndef ENGINE_H
#define ENGINE_H


#include <iostream>
#include "../shared/DebugManager.h"
#include <allegro5/allegro.h>
#include <allegro5/allegro_font.h>
#include <allegro5/allegro_primitives.h>
#include "allegro5/allegro_audio.h"
#include <allegro5/allegro_image.h>
#include "allegro5/allegro_native_dialog.h"
#include "VideoSettings.h"
#include "Display.h"
#include <mutex>
#include <semaphore>
#include <thread>
#include <string>

class SoundDevice;
class Debugmanager;
class ConnectionManager;
class KeyboardDevice;
class Debugger;

using namespace std;

class Engine {

private:
	KeyboardDevice *mKeyboardDevice = NULL;

public:
	// Debugger state
	enum RunState {
		ENG_RUN, ENG_HALT, ENG_STEP, ENG_STEP_OVER, ENG_X_BRK_WAIT,
		ENG_R_BRK_WAIT, ENG_R_V_BRK_WAIT,
		ENG_W_BRK_WAIT, ENG_W_V_BRK_WAIT,
		ENG_RW_BRK_WAIT, ENG_RW_V_BRK_WAIT,
		ENG_BRK_DET, ENG_WAIT_ON_RET,
		ENG_TBD // Only used intially to indicate that the user hasn't specified an initial mode
	};
#define _ENGINE_STATE(x) (\
	x==ENG_RUN?"Run":\
	(x==ENG_HALT?"Halt":\
		(x==ENG_STEP?"Step":\
			(x==ENG_X_BRK_WAIT?"Break on execution":\
				(x==ENG_R_BRK_WAIT?"Wait on read address":\
					(x==ENG_R_V_BRK_WAIT?"Wait on read value":\
						(x==ENG_W_BRK_WAIT?"Wait on write address":\
							(x==ENG_W_V_BRK_WAIT?"Wait on written value":\
								(x==ENG_RW_BRK_WAIT?"Wait on read or write to address":\
									(x==ENG_RW_V_BRK_WAIT?"Wait on read or written value":\
										(x==ENG_BRK_DET?"Breakpoint triggered":(x==ENG_STEP_OVER?"Step over":\
											(x==ENG_WAIT_ON_RET?"Wait on return from subroutine":(x==ENG_TBD?"TBD":"???")))\
										)\
									)\
								)\
							)\
						)\
					)\
				)\
			)\
		)\
	)\
)

private:

	Display* mDisplay = NULL;


	uint64_t mCycleCount = 0;
	bool mQuit = false;

	DeviceManager* mDeviceManager = nullptr;

	VideoDisplayUnit* mVDU = NULL;
	SoundDevice* mSoundDevice = NULL;
	vector<Device*> mEmulationPeriodScheduledDevices, mHighRateScheduledDevices, mInstrScheduledDevices;
	P6502* mMicroprocessor = NULL;
	double mCPUClock = 1.0;

	ALLEGRO_EVENT_QUEUE* mQueue = NULL;
	ALLEGRO_TIMER* mEmulationTimer = NULL;

	DebugManager *mDM = NULL;
	bool mRecurringTracing = false;

	ConnectionManager *mConnectionManager = NULL;


	GUI *mGUI = nullptr;
	Debugger* mDebugger = nullptr;


	RunState mState = ENG_RUN;
	int mSteps = 0;
	int mBreakAdr = -1;
	uint8_t mReadData = 0xff;
	uint8_t mWrittenData = 0xff;
	uint16_t mOperandAddress = 0xffff;

	bool mBreakPoint = false;
	RunState mBreakPointMode = ENG_TBD;

	uint16_t mRetAdr = 0x0;

	// Create mutex for debug purpose
	mutex mExecMutex;

	// Directory for storing files generated by Debugger and more
	string mOutDir;

	bool mKeyPressed = false;

	// Base synchronisation rate for emulation
	double mLowEmulationRate = 50;
	double mHighEmulationRate = mLowEmulationRate * 625;

	// Emulation speed
	double mSpeedFactor = 1;
	double pSpeedFactor = 2;

	double mTimerRate = mLowEmulationRate * mSpeedFactor;
	int mTimerRateInt = (int) round(mTimerRate);

	int mEmulationCycle = 0;

	uint16_t mCPURetAdr = 0x0;

	bool allegroInit();

	bool toggleTracing(DebugLevel level);

	// Check for user key input
	void checkForUserInput();

	// Check for triggering of a breakpoint
	void checkForBreakPoint();

	// Check for change in emulation speed
	void checkForSpeedChange();

	bool setBreakPointAndWait();

public:

	Engine(string mapFileName, Program &program, Program &data, double emulationSpeed, VideoFormat videoFormat, bool enableHWAcc,
		DebugManager *debugManager, string outDir, RunState initialState);
	~Engine();

	bool run();

	bool halt();

	bool cont();

	bool step(int n, bool stepOver);
	bool step(int n);

	bool setBreakPointAndWait(RunState mode, uint16_t adr, uint8_t &readData, uint8_t &writtenData, uint16_t &operandAdr, bool repetition);

	bool clrBreakPoint();

	bool isRunning() { return mState != ENG_HALT && mState != ENG_BRK_DET; }

	string getState() { return _ENGINE_STATE(mState); }
};


#endif