#ifndef ENGINE_H
#define ENGINE_H


#include <iostream>
#include "../shared/DebugTracing.h"
#include <allegro5/allegro.h>
#include <allegro5/allegro_font.h>
#include <allegro5/allegro_primitives.h>
#include "allegro5/allegro_audio.h"
#include <allegro5/allegro_image.h>
#include "allegro5/allegro_native_dialog.h"
#include "VideoSettings.h"
#include "Display.h"
#include <mutex>
#include <semaphore>
#include <thread>
#include <string>
#include <fstream>
#include <array>
#include "TimedDevice.h"

class SoundDevice;
class Debugmanager;
class ConnectionManager;
class KeyboardDevice;
class Debugger;

using namespace std;

class Engine {

public:

	enum RunState {
		ENG_TBD = 0x000,		// 0000 0000 0000	Only used intially to indicate that the user hasn't specified an initial mode
		ENG_HALT = 0x010,		// 0000 0001 0000
		ENG_BRK_DET = 0x300,		// 0011 0000 0000
		ENG_RUN = 0x800,		// 1000 0000 0000
		ENG_STEP = 0x900,		// 1001 0000 0000
		ENG_STEP_OVER = 0x910,		// 1001 0001 0000
		ENG_X_BRK_WAIT = 0xa00,		// 1010 0000 0000
		ENG_R_BRK_WAIT = 0xa10,		// 1010 0001 0000
		ENG_R_V_BRK_WAIT = 0xa51,		// 1010 0101 0001
		ENG_W_BRK_WAIT = 0xa20,		// 1010 0010 0000
		ENG_W_V_BRK_WAIT = 0xa61,		// 1010 0110 0001
		ENG_RW_BRK_WAIT = 0xa30,		// 1010 0011 0000
		ENG_RW_V_BRK_WAIT = 0xa71,		// 1010 0111 0001
		ENG_WAIT_ON_RET = 0xc00		// 1100 0000 0000
	};
#define _BRK_ANY_WAIT(x)	( x & 0x200          )	// xx1x xxxx xxxx
#define	_BRK_R_WAIT(x)		((x & 0x250) == 0x210)	// xx1x x0x1 xxxx
#define _BRK_W_WAIT(x)		((x & 0x260) == 0x220)	// xx1x x01x xxxx
#define	_BRK_R_VAL_WAIT(x)	((x & 0x250) == 0x250)	// xx1x x1x1 xxxx
#define _BRK_W_VAL_WAIT(x)	((x & 0x260) == 0x260)	// xxx1 x11x xxxx
#define _CPU_RUNNING(x)		( x & 0x800          )	// 1xxx xxxx xxxx

#define _ENGINE_STATE(x) (\
	x==ENG_RUN?"Run":\
	(x==ENG_HALT?"Halt":\
		(x==ENG_STEP?"Step":\
			(x==ENG_X_BRK_WAIT?"Break on execution":\
				(x==ENG_R_BRK_WAIT?"Wait on read address":\
					(x==ENG_R_V_BRK_WAIT?"Wait on read value":\
						(x==ENG_W_BRK_WAIT?"Wait on write address":\
							(x==ENG_W_V_BRK_WAIT?"Wait on written value":\
								(x==ENG_RW_BRK_WAIT?"Wait on read or write to address":\
									(x==ENG_RW_V_BRK_WAIT?"Wait on read or written value":\
										(x==ENG_BRK_DET?"Breakpoint triggered":(x==ENG_STEP_OVER?"Step over":\
											(x==ENG_WAIT_ON_RET?"Wait on return from subroutine":(x==ENG_TBD?"TBD":"???")))\
										)\
									)\
								)\
							)\
						)\
					)\
				)\
			)\
		)\
	)\
)

private:

	Display* mDisplay = NULL;

	int mTracingCount = 0;
	int mTracingCountMax = -1;

	uint64_t mTicks = 0;
	bool mQuit = false;

	DeviceManager* mDeviceManager = nullptr;

	VideoDisplayUnit* mVDU = NULL;
	SoundDevice* mSoundDevice = NULL;
	vector<TimedDevice*> mEmulationPeriodScheduledDevices, mHighRateScheduledDevices, mInstrScheduledDevices;
	vector<Device*> mDevices;
	P6502* mMicroprocessor = NULL;
	double mTickRate = 1.0;

	ALLEGRO_EVENT_QUEUE* mQueue = NULL;
	ALLEGRO_TIMER* mEmulationTimer = NULL;

	DebugTracing* mDT = NULL;
	bool mRecurringTracing = false;

	ConnectionManager* mConnectionManager = NULL;


	GUI* mGUI = nullptr;
	Debugger* mDebugger = nullptr;


	RunState mState = ENG_RUN;
	int mSteps = 0;
	int mBreakAdr = -1;
	uint8_t mReadData = 0xff;
	uint8_t mWrittenData = 0xff;
	uint16_t mOperandAddress = 0xffff;

	bool mBreakPoint = false;
	RunState mBreakPointMode = ENG_TBD;

	uint16_t mRetAdr = 0x0;

	// Create mutex for debug purpose
	mutex mExecMutex;

	// Directory for storing files generated by Debugger and more
	string mOutDir;

	bool mKeyPressed = false;

	// Base synchronisation rate for emulation
	double mLowEmulationRate = 50;
	double mHighEmulationRate = mLowEmulationRate * 625;

	// Emulation speed
	double mSpeedFactor = 1;
	double pSpeedFactor = 2;

	double mTimerRate = mLowEmulationRate * mSpeedFactor;
	int mTimerRateInt = (int)round(mTimerRate);

	int mEmulationCycle = 0;

	uint16_t mCPURetAdr = 0x0;

	bool allegroInit();

	// Check for triggering of a breakpoint
	void checkForBreakPoint();

	// Check for change in emulation speed
	void checkForSpeedChange();

	bool setBreakPointAndWait(ostream& sout);

	void logInstr();

	int mBufWindowReadIndex = 0;
	int mBufWindowWriteIndex = 0;
	int mBufferInstrSize = 0;
	int mBufWinSz = 10;
	bool mBreakWindowEnabled = false;
	void updateLogWindow();
	void clrLogWindow();




	vector<InstrLogData> mInstrLogBuffer;
#define ENGINE_BUF_WINDOW_SZ	100
	vector<InstrLogData> mInstrBufferWindow = vector<InstrLogData>(ENGINE_BUF_WINDOW_SZ);

	vector<DevicePort*> mLoggedPorts;
#define ENGINE_LOGGED_PORTS_MAX 25
	typedef array<uint8_t, ENGINE_LOGGED_PORTS_MAX> PortValues;
	vector<PortValues> mPortLogBuffer;
	vector<PortValues> mPortBufferWindow = vector<PortValues>(ENGINE_BUF_WINDOW_SZ);

	PortValues mTmpLoggedPortValues = { 0 };

	// Logging of device's serialised state
	vector<Device*> mLoggedDevices;
	vector<SerialisedStates> mSerialisedLogBuffer;
	vector<SerialisedStates> mPSerialisedBufferWindow = vector<SerialisedStates>(ENGINE_BUF_WINDOW_SZ);
	SerialisedStates mTmpSerialisedStates = { 0 };

public:

	Engine(string mapFileName, VideoFormat videoFormat, bool enableHWAcc,
		DebugTracing* debugTracing, string outDir, RunState initialState);
	~Engine();

	bool limitTracing(int n) {
		if (mDebugger != nullptr) {
			mTracingCountMax = n;
			return true;
		}
		else return false;
	}

	bool run();

	bool halt();

	bool cont(ostream& sout);

	bool reset();

	bool step(int n, bool stepOver);
	bool step(int n);

	bool setBreakPointAndWait(ostream& sout, RunState mode, uint16_t adr, uint8_t& readData, uint8_t& writtenData, uint16_t& operandAdr, bool repetition, bool enableTrace);

	bool clrBreakPoint();

	bool isRunning() { return _CPU_RUNNING(mState); }

	string getState() { return _ENGINE_STATE(mState); }

	void printInstrLog(ostream& sout);

	void printInstrWindow(ostream& sout);

	bool enableLogWindow(int sz);
	void disableLogWindow();

	bool setLoggedPorts(vector<DevicePort*> loggedPorts);
	bool setLoggedDevices(vector<Device*> loggedDevices);

	bool getLoggedPorts(vector<DevicePort*>*& loggedPorts) { loggedPorts = &mLoggedPorts; return true; }
	bool getLoggedDevices(vector<Device*>*& loggedDevices) { loggedDevices = &mLoggedDevices; return true; }

	string getBreakPointInfo();

};

#endif