#ifndef ENGINE_H
#define ENGINE_H


#include <iostream>
#include "../shared/DebugManager.h"
#include <allegro5/allegro.h>
#include <allegro5/allegro_font.h>
#include <allegro5/allegro_primitives.h>
#include "allegro5/allegro_audio.h"
#include <allegro5/allegro_image.h>
#include "allegro5/allegro_native_dialog.h"
#include "VideoSettings.h"
#include "Display.h"
#include <mutex>
#include <semaphore>
#include <thread>

class SoundDevice;
class Debugmanager;

using namespace std;

class Engine {

public:
	// Debugger state
	enum RunState {
		ENG_RUN, ENG_HALT, ENG_STEP, ENG_STEP_OVER, ENG_X_BRK_WAIT,
		ENG_R_BRK_WAIT, ENG_R_V_BRK_WAIT,
		ENG_W_BRK_WAIT, ENG_W_V_BRK_WAIT,
		ENG_RW_BRK_WAIT, ENG_RW_V_BRK_WAIT,
		ENG_BRK_DET, ENG_WAIT_ON_RET
	};
#define _ENGINE_STATE(x) (\
	x==ENG_RUN?"Run":\
	(x==ENG_HALT?"Halt":\
		(x==ENG_STEP?"Step":\
			(x==ENG_X_BRK_WAIT?"Break on execution":\
				(x==ENG_R_BRK_WAIT?"Wait on read address":\
					(x==ENG_R_V_BRK_WAIT?"Wait on read value":\
						(x==ENG_W_BRK_WAIT?"Wait on write address":\
							(x==ENG_W_V_BRK_WAIT?"Wait on written value":\
								(x==ENG_RW_BRK_WAIT?"Wait on read or write to address":\
									(x==ENG_RW_V_BRK_WAIT?"Wait on read or written value":\
										(x==ENG_BRK_DET?"Breakpoint triggered":(x==ENG_STEP_OVER?"Step over":\
											(x==ENG_WAIT_ON_RET?"Wait on return from subroutine":"???"))\
										)\
									)\
								)\
							)\
						)\
					)\
				)\
			)\
		)\
	)\
)

private:

	Display* mDisplay = NULL;

	double mSpeedFactor = 1;

	uint64_t mCycleCount = 0;
	bool mQuit = false;
	int mFieldRate = 50;

	Devices* mDevices = NULL;

	VideoDisplayUnit* mVDU = NULL;
	SoundDevice* mSoundDevice = NULL;
	vector<Device*> mFieldScheduledDevices, mHalfLineScheduledDevices, mInstrScheduledDevices;
	P6502* mMicroprocessor = NULL;
	double mCPUClock = 1.0;

	ALLEGRO_DISPLAY* mAllegroDisplay = NULL;
	ALLEGRO_EVENT_QUEUE* mQueue = NULL;
	ALLEGRO_TIMER* mfieldTimer = NULL;

	DebugManager *mDM = NULL;
	bool mRecurringTracing = false;


	GUI *mGUI = NULL;


	RunState mState = ENG_RUN;
	int mSteps = 0;
	int mBreakAdr = -1;
	uint8_t mReadData = 0xff;
	uint8_t mWrittenData = 0xff;
	uint16_t mOperandAddress = 0xffff;

	uint16_t mRetAdr = 0x0;

	// Create mutex for debug purpose
	mutex mExecMutex;

	// Directory for storing files generated by Debugger and more
	string mOutDir;

	bool allegroInit();

	bool toggleTracing(DebugLevel level);

public:

	Engine(string mapFileName, Program &program, Program &data, double emulationSpeed, VideoFormat videoFormat, bool enableHWAcc,
		DebugManager *debugManager, string outDir);
	~Engine();

	bool run();

	bool halt();

	bool cont();

	bool step(int n, bool stepOver);
	bool step(int n);

	bool setBreakPointAndWait(RunState mode, uint16_t adr, uint8_t &readData, uint8_t &writtenData, uint16_t &operandAdr, bool repetition);
};


#endif